---
abstract: 'maintain and search a minimal CPAN database'
author:
  - 'Serguei Trouchelle <stro@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-SQLite
provides:
  CPAN::SQLite:
    file: lib/CPAN/SQLite.pm
    version: 0.201
  CPAN::SQLite::DBI:
    file: lib/CPAN/SQLite/DBI.pm
    version: 0.201
  CPAN::SQLite::DBI::Index:
    file: lib/CPAN/SQLite/DBI/Index.pm
    version: 0.201
  CPAN::SQLite::DBI::Index::auths:
    file: lib/CPAN/SQLite/DBI/Index.pm
  CPAN::SQLite::DBI::Index::chaps:
    file: lib/CPAN/SQLite/DBI/Index.pm
  CPAN::SQLite::DBI::Index::dists:
    file: lib/CPAN/SQLite/DBI/Index.pm
  CPAN::SQLite::DBI::Index::mods:
    file: lib/CPAN/SQLite/DBI/Index.pm
  CPAN::SQLite::DBI::Search:
    file: lib/CPAN/SQLite/DBI/Search.pm
    version: 0.201
  CPAN::SQLite::DBI::Search::auths:
    file: lib/CPAN/SQLite/DBI/Search.pm
  CPAN::SQLite::DBI::Search::chaps:
    file: lib/CPAN/SQLite/DBI/Search.pm
  CPAN::SQLite::DBI::Search::dists:
    file: lib/CPAN/SQLite/DBI/Search.pm
  CPAN::SQLite::DBI::Search::mods:
    file: lib/CPAN/SQLite/DBI/Search.pm
  CPAN::SQLite::Index:
    file: lib/CPAN/SQLite/Index.pm
    version: 0.201
  CPAN::SQLite::Info:
    file: lib/CPAN/SQLite/Info.pm
    version: 0.201
  CPAN::SQLite::META:
    file: lib/CPAN/SQLite/META.pm
    version: 0.201
  CPAN::SQLite::META::Author:
    file: lib/CPAN/SQLite/META.pm
  CPAN::SQLite::META::Bundle:
    file: lib/CPAN/SQLite/META.pm
  CPAN::SQLite::META::Distribution:
    file: lib/CPAN/SQLite/META.pm
  CPAN::SQLite::META::Module:
    file: lib/CPAN/SQLite/META.pm
  CPAN::SQLite::Populate:
    file: lib/CPAN/SQLite/Populate.pm
    version: 0.201
  CPAN::SQLite::Populate::auths:
    file: lib/CPAN/SQLite/Populate.pm
  CPAN::SQLite::Populate::chaps:
    file: lib/CPAN/SQLite/Populate.pm
  CPAN::SQLite::Populate::dists:
    file: lib/CPAN/SQLite/Populate.pm
  CPAN::SQLite::Populate::mods:
    file: lib/CPAN/SQLite/Populate.pm
  CPAN::SQLite::Search:
    file: lib/CPAN/SQLite/Search.pm
    version: 0.201
  CPAN::SQLite::Search::author:
    file: lib/CPAN/SQLite/Search.pm
  CPAN::SQLite::Search::dist:
    file: lib/CPAN/SQLite/Search.pm
  CPAN::SQLite::Search::module:
    file: lib/CPAN/SQLite/Search.pm
  CPAN::SQLite::State:
    file: lib/CPAN/SQLite/State.pm
    version: 0.201
  CPAN::SQLite::State::auths:
    file: lib/CPAN/SQLite/State.pm
  CPAN::SQLite::State::dists:
    file: lib/CPAN/SQLite/State.pm
  CPAN::SQLite::State::mods:
    file: lib/CPAN/SQLite/State.pm
  CPAN::SQLite::Util:
    file: lib/CPAN/SQLite/Util.pm
    version: 0.201
  CPAN::SQLite::Version:
    file: lib/CPAN/SQLite/Util.pm
    version: 0.1
requires:
  Archive::Tar: 1.08
  CPAN::DistnameInfo: 0.09
  Compress::Zlib: 0
  DBD::SQLite: 1.27
  File::HomeDir: 0
  File::Spec: 0
  IO::Zlib: 0
  LWP::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://svn.trouchelle.com/perlmodules/CPAN-SQLite/
version: 0.201
