--- #YAML:1.0
name:               CPAN-SQLite
version:            0.204
abstract:           maintain and search a minimal CPAN database
author:
    - Serguei Trouchelle <stro@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Tar:        1.54
    Compress::Zlib:      0
    CPAN::DistnameInfo:  0.09
    CPAN::Index:         1.93
    DBD::SQLite:         1.27
    File::HomeDir:       0
    File::Spec:          0
    IO::Zlib:            0
    LWP::Simple:         0
    parent:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
